server:
  port: 7080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml

spring:
  restclient:
    connect-timeout: 5s
    read-timeout: 10s
  mvc:
    problemdetails:
      enabled: true
  web:
    locale: en
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    use-code-as-default-message: true
    cache-duration: 1h
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  application:
    name: spring-sso-samples
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  cache:
    default-config:
      ttl: 1h
      initial-capacity: 5000
      maximum-size: 10000
    hibernate:
      default-update-timestamps-region:
        ttl: 1h
        initial-capacity: 5000
        maximum-size: 10000
      default-query-results-region:
        ttl: 1h
        initial-capacity: 5000
        maximum-size: 10000
    cache-names:
      - oauth2AuthorizationEntity
      - oauth2AuthorizationEntityBySpecification
      - oauth2AuthorizationConsentEntity
      - oauth2ClientEntity
      - oauth2ClientEntity.clientScopes
      - oauth2ClientEntityByClientId
      - oauth2ClientEntityCountByClientId
      - oauth2ClientEntityCountByClientSecret
      - oauth2ScopeEntity
      - oauth2ClientScopeMappingEntity
      - roleEntity
      - roleEntityByName
      - userEntity
      - userEntity.userRoles
      - userEntityByUsername
      - userEntityByEmail
      - userRoleMappingEntity

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    io.github.susimsek.springssosamples: INFO
  pattern: '%clr(%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}){faint} %clr(%5p){highlight} %clr(${PID:- }){magenta} --- [%clr(${spring.application.name:-}){green},%X{traceId:-},%X{spanId:-}] [%clr(%t){faint}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%clr(%wEx){red}'
  async:
    queueSize: 10000
    discardingThreshold: 0
    maxFlushTime: 5000
    includeCallerData: false
  loki:
    enabled: false
    url: http://localhost:3100/loki/api/v1/push
    inner-threads-expiration: 5m
    batch-max-items: 1000
    batch-max-bytes: 2MB
    batch-timeout: 5s
    use-direct-buffers: true
    drain-on-stop: true
    metrics-enabled: false
    drop-rate-limited-batches: false
    verbose: false
    internal-queues-check-timeout: 25ms
    retry:
      max-retries: 3
      min-retry-backoff: 500ms
      max-retry-backoff: 1m
      max-retry-jitter: 500ms
  aspect:
    enabled: true
    log-level: FULL
  http:
    enabled: true
    log-level: FULL
  obfuscate:
    enabled: true
    mask-value: "****"
    headers:
      - Authorization
      - Cookie
      - Set-Cookie
      - X-API-Key
      - X-CSRF-Token
      - WWW-Authenticate
      - X-JWS-Signature
    parameters:
      - key
      - password
      - token
      - secret
      - api_key
      - access_token
      - refresh_token
      - jws_token
      - jwe_token
    json-body-fields:
      - $.token
      - $.access_token
      - $.refresh_token
      - $.id_token
      - $.email
      - $.secretKey
      - $.apiSecret
      - $.apiKey
      - $.jwsToken
      - $.jweToken
    method-fields:
      - $.token
      - $.accessToken
      - $.refreshToken
      - $.idToken
      - $.email
      - $.secretKey
      - $.apiSecret
      - $.apiKey
      - $.jwsToken

springdoc:
  swagger-ui:
    operationsSorter: method
    defaultModelsExpandDepth: -1
    display-request-duration: true
    filter: true
    show-extensions: true
    try-it-out-enabled: true
    persist-authorization: true
  show-actuator: false
