# This configuration is intended for development purpose
version: "3.8"

services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.10
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - 3100:3100
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - loki:/loki

networks:
  sso:
    driver: "bridge"

volumes:
  loki:
